# Generated by Django 5.1.5 on 2025-01-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prescriptions",
            "0002_dose_is_missed_dose_is_valid_alter_dose_quantity_and_more",
        ),
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="reminder_body",
        ),
        migrations.AddField(
            model_name="reminder",
            name="dose",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="prescriptions.dose",
            ),
        ),
    ]
