services:
  - type: web
    name: medicalchain-prod
    runtime: python
    plan: free
    branch: mchain
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r medicalchain/requirements/prod.txt
      cd medicalchain/frontend && npm install && npm run build
      cd ../..
      python medicalchain/manage.py collectstatic --noinput
      python medicalchain/manage.py migrate --noinput

    startCommand: gunicorn medicalchain.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120

    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_SETTINGS_MODULE
        value: medicalchain.settings.prod
      - key: SECRET_KEY
        generateValue: true  # Render génère automatiquement une clé sécurisée
      - key: ALLOWED_HOSTS
        value: "medicalchain-prod.onrender.com"  # À adapter avec votre URL réelle
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: DATABASE_URL
        fromDatabase:
          name: medicalchain_db  # Créez cette base de données séparément
          property: connectionString

    autoDeploy: yes
    healthCheckPath: /health-check/