# Generated by Django 5.1.5 on 2025-02-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_time", models.DateTimeField()),
                ("dose_taken", models.BooleanField(default=False)),
                ("notification_sent", models.BooleanField(default=False)),
                (
                    "dose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.dose",
                    ),
                ),
            ],
        ),
    ]
