# Generated by Django 5.1.5 on 2025-04-13 13:09

import backend.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_alter_customuser_options_customuser_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="current_address",
            field=models.CharField(max_length=255, verbose_name="Current Address"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="current_function",
            field=models.CharField(max_length=255, verbose_name="Profession/Function"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=60, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=60, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default=backend.apps.users.models.get_default_profile_image,
                null=True,
                upload_to=backend.apps.users.models.user_profile_image_path,
                verbose_name="Profile Image",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Username"
            ),
        ),
    ]
