# Generated by Django 5.1.5 on 2025-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_current_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="current_address",
            field=models.CharField(
                default="", max_length=255, verbose_name="Current Address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="current_function",
            field=models.CharField(
                default="", max_length=255, verbose_name="Profession/Function"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                default="", max_length=60, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                default="O",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="", max_length=60, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=15,
                null=True,
                verbose_name="Username",
            ),
        ),
    ]
