# Generated by Django 5.0.6 on 2025-06-16 12:00

import backend.apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_current_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified_doctor",
            field=models.BooleanField(
                default=False, verbose_name="Verified Doctor Status"
            ),
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "professional_id",
                    models.CharField(
                        max_length=50, verbose_name="Professional ID/License Number"
                    ),
                ),
                (
                    "license_country",
                    models.CharField(
                        max_length=100, verbose_name="License Country/Region"
                    ),
                ),
                (
                    "diploma",
                    models.CharField(max_length=100, verbose_name="Main Diploma"),
                ),
                (
                    "graduation_year",
                    models.PositiveIntegerField(verbose_name="Graduation Year"),
                ),
                (
                    "speciality",
                    models.CharField(max_length=100, verbose_name="Medical Speciality"),
                ),
                (
                    "hospital",
                    models.CharField(max_length=100, verbose_name="Hospital/Clinic"),
                ),
                (
                    "professional_email",
                    models.EmailField(
                        max_length=254, verbose_name="Professional Email"
                    ),
                ),
                (
                    "professional_phone",
                    models.CharField(max_length=20, verbose_name="Professional Phone"),
                ),
                (
                    "city_country",
                    models.CharField(
                        max_length=100, verbose_name="City/Country of Practice"
                    ),
                ),
                ("bio", models.TextField(verbose_name="Professional Bio")),
                (
                    "diploma_copy",
                    models.FileField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="Diploma Copy",
                    ),
                ),
                (
                    "id_copy",
                    models.FileField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="ID Copy",
                    ),
                ),
                (
                    "professional_photo",
                    models.ImageField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="Professional Photo",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="CV",
                    ),
                ),
                (
                    "malpractice_insurance",
                    models.FileField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="Malpractice Insurance",
                    ),
                ),
                (
                    "references",
                    models.FileField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="References",
                    ),
                ),
                (
                    "payment_methods",
                    models.JSONField(default=list, verbose_name="Payment Methods"),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        upload_to=backend.apps.users.models.doctor_document_path,
                        verbose_name="Payment Proof",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_extra_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
            },
        ),
    ]
