# Configuration de pre-commit pour le formatage et l'analyse du code Python
repos:
  - repo: https://github.com/psf/black  # Dépôt officiel de Black
    rev: 25.1.0  # Dernière version stable
    hooks:
      - id: black
        language_version: python3  # Utilise la version actuelle de Python
        args: ["--line-length=88"]  # Alignement avec Flake8

  - repo: https://github.com/pycqa/flake8  # Dépôt officiel de Flake8
    rev: 7.1.1  # Dernière version stable
    hooks:
      - id: flake8
        files: \.py$
        language_version: python3  # Utilise la version actuelle de Python
        args: 
          - "--max-line-length=88"
          - "--extend-ignore=E501,W391,E401"  # Ignore les erreurs E401 liées aux imports
