services:
  - type: web
    name: medicalchain-prod
    runtime: python
    plan: free
    branch: mchain
    
    buildCommand: |
      pip install -r medicalchain/requirements/prod.txt
      cd medicalchain/frontend && npm install && npm run build
      cd ../..
      python medicalchain/manage.py collectstatic --noinput

    startCommand: gunicorn medicalchain.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120

    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_SETTINGS_MODULE  # Nécessaire pour Django
        value: medicalchain.settings.prod
      - key: SECRET_KEY
        value: votre_clé_secrète
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: DATABASE_URL  # Si vous utilisez PostgreSQL
        value: postgresql://user:password@host:port/dbname

    autoDeploy: yes
    healthCheckPath: /health-check/