# Generated by Django 5.1.5 on 2025-02-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taking_time", models.TimeField()),
                ("quantity", models.FloatField()),
                ("is_valid", models.BooleanField(default=False)),
                ("is_missed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Dose",
                "verbose_name_plural": "Doses",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
            },
        ),
    ]
