# Generated by Django 5.1.5 on 2025-02-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_transactionhistory_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="user",
        ),
    ]
