# Generated by Django 5.1.5 on 2025-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_remove_transactionhistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("payment", "Payment")],
                default="payment",
                max_length=50,
            ),
        ),
    ]
