# Generated by Django 5.1.5 on 2025-03-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_rename_date_transactionhistory_transaction_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="transaction_date",
            new_name="date",
        ),
    ]
