# Generated by Django 5.1.5 on 2025-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_rename_transaction_date_transactionhistory_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="day_of_week",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="time",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
