# Generated by Django 5.1.5 on 2025-03-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
        ("payments", "0017_alter_transactionhistory_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="appointment_reason",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.appointment",
            ),
        ),
    ]
