# Generated by Django 5.1.5 on 2025-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("appointment_payment", "Appointment Payment"),
                ],
                default="appointment_payment",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="description",
            field=models.TextField(
                blank=True, default="No description provided", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("appointment_payment", "Appointment Payment"),
                ],
                max_length=50,
            ),
        ),
    ]
