# Generated by Django 5.1.5 on 2025-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_payment_created_at_transactionhistory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("medicalchain_wallet", "MedicalChain Wallet"),
                    ("mobile_money", "Mobile Money"),
                    ("card", "Bank Card"),
                    ("cryptocurrency", "Cryptocurrency"),
                ],
                default="medicalChain_wallet",
                max_length=20,
            ),
        ),
    ]
