# Generated by Django 5.1.5 on 2025-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("medicalchain_wallet", "MedicalChain Wallet"),
                ],
                default="medicalchain_wallet",
                max_length=20,
            ),
        ),
    ]
