# Generated by Django 5.1.5 on 2025-03-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_alter_payment_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="date",
            new_name="transaction_date",
        ),
    ]
