# Generated by Django 5.1.5 on 2025-03-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_payment_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Wallet",
                to="payments.wallet",
            ),
        ),
    ]
