# Generated by Django 5.1.5 on 2025-03-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
        ("payments", "0018_transactionhistory_appointment_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="appointment_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.appointment",
            ),
        ),
    ]
