# Generated by Django 5.0.6 on 2025-05-25 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=100, unique=True)),
                ("network", models.CharField(max_length=50)),
                ("contract_address", models.CharField(max_length=100)),
                ("block_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gas_used",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=50, null=True
                    ),
                ),
                (
                    "gas_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blockchain Transaction",
                "verbose_name_plural": "Blockchain Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_payment_8ac9aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_payment_114518_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionhistory",
            name="payments_tr_transac_e177aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionhistory",
            name="payments_tr_date_626541_idx",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_type",
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="time",
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="blockchain_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="blockchain_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="network",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="blockchain_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Blockchain Address"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_category",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile Money"),
                    ("crypto", "Cryptocurrency"),
                    ("card", "Credit/Debit Card"),
                    ("wallet", "Medichain Wallet"),
                    ("doctor_subscription", "Doctor Subscription"),
                ],
                default="wallet",
                max_length=20,
                verbose_name="Payment category",
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("blockchain", "Blockchain"),
                ],
                default="deposit",
                max_length=50,
                verbose_name="Transaction type",
            ),
        ),
        migrations.AddField(
            model_name="blockchaintransaction",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blockchain_transactions",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="blockchain_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.blockchaintransaction",
                verbose_name="Blockchain reference",
            ),
        ),
    ]
