# Generated by Django 5.1.5 on 2025-02-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="specialty",
            new_name="speciality",
        ),
    ]
