# Generated by Django 5.1.5 on 2025-02-27 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_rename_specialty_doctor_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
