# Generated by Django 5.1.5 on 2025-04-15 09:13

import backend.apps.doctors.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_doctor_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="city_country",
            field=models.CharField(
                default="Bujumbura, Burundi",
                max_length=100,
                verbose_name="City/Country of Practice",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="diploma",
            field=models.CharField(
                default="Doctor of Medicine",
                max_length=100,
                verbose_name="Main Diploma",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="diploma_copy",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.apps.doctors.models.doctor_diploma_path,
                verbose_name="Diploma Copy",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="graduation_year",
            field=models.PositiveIntegerField(
                default=2020, verbose_name="Graduation Year"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="id_copy",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.apps.doctors.models.doctor_id_path,
                verbose_name="ID Copy",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="license_country",
            field=models.CharField(
                default="Burundi", max_length=100, verbose_name="License Country/Region"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="payment_methods",
            field=models.JSONField(
                default=backend.apps.doctors.models.default_payment_methods,
                verbose_name="Accepted Payment Methods",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="payment_proof",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.apps.doctors.models.doctor_payment_path,
                verbose_name="Payment Proof",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="professional_email",
            field=models.EmailField(
                default="example@example.com",
                max_length=254,
                verbose_name="Professional Email",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="professional_id",
            field=models.CharField(
                default="N/A",
                max_length=100,
                verbose_name="Professional ID/License Number",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="professional_phone",
            field=models.CharField(
                default="+25712345678", max_length=20, verbose_name="Professional Phone"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="professional_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.apps.doctors.models.doctor_photo_path,
                verbose_name="Professional Photo",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="subscription_plan",
            field=models.CharField(
                choices=[("premium", "Premium"), ("basic", "Basic")],
                default="basic",
                max_length=20,
                verbose_name="Subscription Plan",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="terms_accepted",
            field=models.BooleanField(default=False, verbose_name="Terms Accepted"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="bio",
            field=models.TextField(
                blank=True,
                default="Experienced medical professional",
                null=True,
                verbose_name="Professional Bio",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="hospital",
            field=models.CharField(
                default="Central Hospital",
                max_length=100,
                verbose_name="Hospital/Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.CharField(
                default="General Medicine",
                max_length=100,
                verbose_name="Medical Speciality",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
